### ISSUE TITLE
Pointer address of argument 0 is NULL

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/DataVec#316] opened 2017-06-13 00:59 UTC
#### Issue Description

See log: https://gist.github.com/crockpotveggies/cdbc3f6950f5dfd0ff766f35e7810a2f

Suddenly started getting this error today, so culprit is fairly new. @kepricon just wondering, did any of your transform stuff make it into master?

#### Version Information

master

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by kepricon** [comment] 2017-06-13 01:30
when did you pull the master?

I only pushed the commit related to the `LargetstBlobCropTransform`.
Other transforms I updated is still pending on my PR(https://github.com/deeplearning4j/DataVec/pull/294)
https://github.com/deeplearning4j/DataVec/commits/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/transform

**Comment by crockpotveggies** [comment] 2017-06-13 01:39
This would have happened in the last ~24 hours. First was using sonatype snapshot, but now it happens when I build locally. Built in last 1 hr.

**Comment by kepricon** [comment] 2017-06-13 02:08
I guess I didn't affect this issue since my PR is not merged as of now.

please see the history below
https://github.com/deeplearning4j/DataVec/commits/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/transform
https://github.com/deeplearning4j/DataVec/commits/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/loader/NativeImageLoader.java

**Comment by kepricon** [comment] 2017-06-13 02:10
Let me investigate javacv end or dl4j end.

**Comment by crockpotveggies** [comment] 2017-06-13 02:31
I wonder if https://github.com/deeplearning4j/DataVec/commit/95623c2bde8dba08a71697a26b9dbae86b83e8a2#diff-a5085aa513942985319e9fd44d6190af is responsible but for some reason I was stuck on an outdated build.

**Comment by papperwing** [comment] 2017-06-13 07:18
I started to get exactly same error after rebuilding two weeks old code. And I am using exactly same pipeline as @crockpotveggies .

**Comment by raver119** [comment] 2017-06-13 08:11
Anybody has simplified code that reproduces this issue?

**Comment by papperwing** [comment] 2017-06-13 10:30
I cannot simply reproduce problem, I extracted from learning process of my NN the preprocess where I download Images put them into dummyRecordReader and processed them and process came completely without problem. Here is added gist:
https://gist.github.com/papperwing/1762c07183b97b73824ccd83ac372ccf

**Comment by raver119** [comment] 2017-06-13 10:31
Sorry, a bit unclear for me: this gist reproduces issue or not?

**Comment by papperwing** [comment] 2017-06-13 10:35
This doesnt. But I cannot figure out what is different than in original.

**Comment by saudet** [comment] 2017-06-13 11:24
It's probably related to changes I made, but it's not obvious what...

**Comment by raver119** [comment] 2017-06-13 11:25
Yep, that's why i'm asking for anything that reproduces this issue. Once we have that - we'll fix it :)

**Comment by papperwing** [comment] 2017-06-13 11:26
I am trying my best to reproduce it but error is not deterministic and I cannot find in debugger what is different.

**Comment by raver119** [comment] 2017-06-13 11:30
Give me anything that might reproduce it, even 5% chance is ok :)

**Comment by papperwing** [comment] 2017-06-13 11:38
Ok I will create zip with .jar, small dataset and startup script. Source will be linked by github repo (https://github.com/papperwing/image-net).

**Comment by AlexDBlack** [comment] 2017-06-28 10:57
Related: https://github.com/deeplearning4j/deeplearning4j/issues/3479

**Comment by saudet** [comment] 2017-06-28 12:08
Hum, deeplearning4j/deeplearning4j#3479 happened before changes I made, so it might not be related after all?

**Comment by raver119** [comment] 2017-06-28 14:30
So, issue is reproducible for me. Here's what i see in debugger.

![screenshot from 2017-06-28 17-28-34](https://user-images.githubusercontent.com/12250879/27642362-4310df88-5c27-11e7-97f8-a6bb8e64bcbf.png)

@saudet under what circumstances OpenCVFrameConverter might return null ptr in Mat?

**Comment by saudet** [comment] 2017-06-29 04:23
@raver119 When the input is invalid, pretty much only null in this case, but it's not. How did you reproduce it?

**Comment by saudet** [comment] 2017-06-29 05:40
Ok, I found the issue. Since Mat are now deallocated promptly, the same address gets easily reused by unrelated objects, while OpenCVFrameConverter would assume that the Mat wrapper object stays the same, but it is not always the case.

**Closed** 2017-06-30 02:59 UTC
