### ISSUE TITLE
datavec TransformProcess schema load Exception

### ISSUE THREAD

**Issue by WinterW** [deeplearning4j/DataVec#568] opened 2018-04-23 04:10 UTC
#### Issue Description
The file is generate by TransformProcess.toJson, then exception when I load it use TransformProcess.fromJson

####  FeatureTransform file: 
> [feature.txt](https://github.com/deeplearning4j/DataVec/files/1936599/feature.txt)

####  ExceptionInfo:
> java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: Argument #1 of constructor [constructor for org.datavec.api.transform.transform.doubletransform.DoubleMathFunctionTransform, annotations: [null]] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator (through reference chain: java.util.ArrayList[80]->org.datavec.api.transform.DataAction["transform"])
	at org.datavec.api.transform.TransformProcess.fromJson(TransformProcess.java:359) ~[datavec-api-0.9.1.jar:?]
	at com.bj58.spider.recom_rank.components.feature.FeatureTransformer.load(FeatureTransformer.java:29) [classes/:?]
	at com.bj58.spider.recom_rank.components.ModelManagerNew.loadOnlineModelInfo(ModelManagerNew.java:126) [classes/:?]
	at com.bj58.spider.recom_rank.components.ModelManagerNew.loads(ModelManagerNew.java:223) [classes/:?]
	at com.bj58.spider.recom_rank.components.RankServiceTest.testGetRankResultForAlogNameAlogTypeSampleList(RankServiceTest.java:85) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:?]
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: Argument #1 of constructor [constructor for org.datavec.api.transform.transform.doubletransform.DoubleMathFunctionTransform, annotations: [null]] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator (through reference chain: java.util.ArrayList[80]->org.datavec.api.transform.DataAction["transform"])
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:267) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:242) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:406) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:176) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:100) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:49) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:240) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[jackson-0.9.1.jar:?]
	at org.datavec.api.transform.TransformProcess.fromJson(TransformProcess.java:357) ~[datavec-api-0.9.1.jar:?]
	... 33 more
Caused by: java.lang.IllegalArgumentException: Argument #1 of constructor [constructor for org.datavec.api.transform.transform.doubletransform.DoubleMathFunctionTransform, annotations: [null]] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
	at org.nd4j.shade.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:508) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:325) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:258) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:216) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:405) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:354) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:262) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:242) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:406) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:176) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:100) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:49) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:240) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562) ~[jackson-0.9.1.jar:?]
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[jackson-0.9.1.jar:?]
	at org.datavec.api.transform.TransformProcess.fromJson(TransformProcess.java:357) ~[datavec-api-0.9.1.jar:?]

#### Version Information
* Datavec version
0.91

**Comment by AlexDBlack** [comment] 2018-04-25 11:45
Thanks for reporting. I was able to reproduce your issue on 0.9.1, but it looks like this has been fixed as of 1.0.0-alpha (I can load your JSON fine on that version).

**Closed by AlexDBlack** 2018-04-25 11:45 UTC
