### ISSUE TITLE
Incorrect overlapping in Spectrogram 

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/DataVec#501] opened 2018-02-06 21:08 UTC
#### Issue Description
When using overlapping > 1 in Spectrogram (line 89-104) the overlapping windows are of size fftSampleSize-1 instead of the expected fftSampleSize used later. Replacing fftSampleSize_1 with 0 fixes the issue so the the expected (at least what I expect :) ) result is produced.

Example:
samples = [0,1,2,3,4,5,6,7]
fftWindowSize = 4
overlap = 2

Expected amplitudes vector:
[0,1,2,3, //First window
 2,3,4,5,  // Second window
 4,5,6,7, // Third window
 6,7,0,0] // Fourth window

Actual amplitudes vector:
[0,1,2,0 // First window
 2,3,4,3 // Second window
 4,5,6,5// Third window
 6,7,0,0 // Fourth window
]  

#### Version Information

Latest version of Spectrogram.java (a8744ac on Jul 10 2017) has the issue. 

#### Contributing

Although it is a trivial fix I'm unsure about how to apply/test it properly, e.g. does it impact any model zoo member or other project and do you need/want to provide backwards compatibility for any models trained using this version.

**Comment by saudet** [comment] 2018-02-07 02:20
Let's mark this as a duplicate of issue #502 and discuss all FFT related issues there. Thanks!

**Closed by saudet** 2018-02-07 02:20 UTC
Labels: bug, duplicate
